[env:tropicon2026]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

build_flags =
    ${esp32s3_base.build_flags}
    -DVARIANT_TROPICON2026
    -DUSE_SX1262
    -I variants/esp32s3/tropicon2026

    # === FLAGS FOR THE TELEMETRY ===
    -DMESHTASTIC_ENABLE_ENVIRONMENTAL_MEASUREMENT
    -DUSE_AHT10
    # ======================================

build_src_filter =
    ${esp32s3_base.build_src_filter}

lib_deps = ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-Arduino_GFX packageName=https://github.com/meshtastic/Arduino_GFX gitBranch=master
  https://github.com/meshtastic/Arduino_GFX/archive/054e81ffaf23784830a734e3c184346789349406.zip