[env:tropicon2026]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

build_flags =
    ${esp32s3_base.build_flags}
    -DVARIANT_TROPICON2026
    -DUSE_SX1262
    -DMESHTASTIC_EXCLUDE_SCREEN=1
    -I variants/esp32s3/tropicon2026

build_src_filter =
    ${esp32s3_base.build_src_filter}